import type { ComponentType } from "react"
import {
  AudioLines,
  Bot,
  Box,
  Code2,
  Columns2,
  Columns3,
  Database,
  ExternalLink,
  FileText,
  FileCode2,
  Film,
  ClipboardList,
  FolderOpen,
  Gamepad2,
  Grid3X3,
  Grid3x2,
  HelpCircle,
  ImageIcon,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  LayoutPanelLeft,
  LayoutPanelTop,
  LayoutTemplate,
  Layers,
  LineChart,
  Map as MapIcon,
  Network,
  Mic,
  ArrowLeftRight,
  PanelLeft,
  PanelLeftOpen,
  PenTool,
  PlayCircle,
  Rows2,
  Rows3,
  Sparkles,
  Table2,
} from "lucide-react"

import type { CardId, CardType } from "../types"

export interface Category {
  id: string
  label: string
  Icon: ComponentType<{ size?: number; strokeWidth?: number }>
  types: CardType[] | "all"
}

export interface LibraryItem {
  id: CardId
  cardType: CardType
  title: string
}

export const CATEGORIES: Category[] = [
  { id: "all", label: "All", Icon: FolderOpen, types: "all" },
  {
    id: "resources",
    label: "Resources",
    Icon: Layers,
    types: ["text", "image", "audio", "video", "animation", "model-3d", "document", "map", "chart", "diagram", "dataset", "embed", "flashcards", "code-snippet", "timeline"],
  },
  {
    id: "activities",
    label: "Activities",
    Icon: Sparkles,
    types: ["chat", "text-editor", "code-editor", "whiteboard", "interactive", "form", "voice-recorder", "sorter"],
  },
  {
    id: "experiences",
    label: "Experiences",
    Icon: Gamepad2,
    types: ["rich-sim", "village-3d", "games"],
  },
  {
    id: "layout",
    label: "Layout",
    Icon: LayoutGrid,
    types: ["layout-split", "layout-stack", "layout-feature", "layout-sidebar", "layout-quad", "layout-mosaic", "layout-triptych", "layout-trirow", "layout-banner", "layout-broadside", "layout-tower", "layout-pinboard", "layout-annotated", "layout-sixgrid", "layout-comparison", "layout-stepped", "layout-hero", "layout-dialogue", "layout-gallery", "layout-spotlight", "layout-flipcard"],
  },
]

export const LIBRARY_ITEMS: LibraryItem[] = [
  { id: "lib-text-1" as CardId, cardType: "text", title: "Marie Curie: A Life of Discovery" },
  { id: "lib-text-2" as CardId, cardType: "text", title: "Leonardo da Vinci: Renaissance Genius" },
  { id: "lib-text-3" as CardId, cardType: "text", title: "The French Revolution: Causes and Effects" },
  { id: "lib-text-4" as CardId, cardType: "text", title: "Natural Selection Explained" },
  { id: "lib-img-1" as CardId, cardType: "image", title: "Renaissance Art Collection" },
  { id: "lib-img-2" as CardId, cardType: "image", title: "Cell Division Diagram" },
  { id: "lib-img-3" as CardId, cardType: "image", title: "Ottoman Empire Territory Map (1683)" },
  { id: "lib-audio-1" as CardId, cardType: "audio", title: "Shakespeare in Conversation" },
  { id: "lib-audio-2" as CardId, cardType: "audio", title: "Lecture: Cell Division" },
  { id: "lib-vid-1" as CardId, cardType: "video", title: "The French Revolution Explained" },
  { id: "lib-vid-2" as CardId, cardType: "video", title: "Evolution: Darwin's Theory" },
  { id: "lib-vid-3" as CardId, cardType: "video", title: "Apollo 11 Launch Footage" },
  { id: "lib-anim-1" as CardId, cardType: "animation", title: "Mitosis — Cell Division" },
  { id: "lib-anim-2" as CardId, cardType: "animation", title: "Plate Tectonics Over 250 Million Years" },
  { id: "lib-3d-1" as CardId, cardType: "model-3d", title: "Airplane — Poly Pizza" },
  { id: "lib-3d-2" as CardId, cardType: "model-3d", title: "Cottage — Poly Pizza" },
  { id: "lib-3d-3" as CardId, cardType: "model-3d", title: "Rocks — Poly Pizza" },
  { id: "lib-doc-1" as CardId, cardType: "document", title: "Newton's Principia Mathematica (excerpt)" },
  { id: "lib-doc-2" as CardId, cardType: "document", title: "Declaration of Independence (1776)" },
  { id: "lib-doc-3" as CardId, cardType: "document", title: "Darwin's On the Origin of Species" },
  { id: "lib-map-1" as CardId, cardType: "map", title: "World Population Density" },
  { id: "lib-map-2" as CardId, cardType: "map", title: "Ottoman Empire at Peak Extent" },
  { id: "lib-map-3" as CardId, cardType: "map", title: "Amazon Rainforest Coverage" },
  { id: "lib-chart-1" as CardId, cardType: "chart", title: "Global Temperature Anomaly 1880–2020" },
  { id: "lib-chart-2" as CardId, cardType: "chart", title: "CO₂ Emissions by Country (2023)" },
  { id: "lib-chart-3" as CardId, cardType: "chart", title: "Human Population Growth 1800–2100" },
  { id: "lib-diag-1" as CardId, cardType: "diagram", title: "Krebs Cycle" },
  { id: "lib-diag-2" as CardId, cardType: "diagram", title: "French Revolution — Cause & Effect" },
  { id: "lib-diag-3" as CardId, cardType: "diagram", title: "OSI Network Model" },
  { id: "lib-table-1" as CardId, cardType: "table", title: "Climate Data 1850–2024" },
  { id: "lib-table-2" as CardId, cardType: "table", title: "Periodic Table — First 20 Elements" },
  { id: "lib-table-3" as CardId, cardType: "table", title: "WW2 Casualties by Country" },
  { id: "lib-ds-1" as CardId, cardType: "dataset", title: "Amazon Rainforest Species Dataset" },
  { id: "lib-ds-2" as CardId, cardType: "dataset", title: "NASA Exoplanet Archive (CSV)" },
  { id: "lib-chat-product-1" as CardId, cardType: "chat", title: "Chat with Darwin" },
  { id: "lib-chat-product-2" as CardId, cardType: "chat", title: "Ada Lovelace Coding Mentor" },
  { id: "lib-text-editor-1" as CardId, cardType: "text-editor", title: "Writing studio" },
  { id: "lib-code-editor-1" as CardId, cardType: "code-editor", title: "Code lab" },
  { id: "lib-whiteboard-1" as CardId, cardType: "whiteboard", title: "Systems whiteboard" },
  { id: "lib-sim-1" as CardId, cardType: "rich-sim", title: "Photosynthesis Process Simulation" },
  { id: "lib-sim-2" as CardId, cardType: "rich-sim", title: "Newton's Cradle — Momentum Lab" },
  { id: "lib-sim-3" as CardId, cardType: "rich-sim", title: "Wave Interference Simulator" },
  { id: "lib-quiz-1" as CardId, cardType: "interactive", title: "French Revolution Knowledge Quiz" },
  { id: "lib-quiz-2" as CardId, cardType: "interactive", title: "Marie Curie: Life and Discoveries Quiz" },
  { id: "lib-quiz-3" as CardId, cardType: "interactive", title: "Photosynthesis Equation Quiz" },
  { id: "lib-quiz-4" as CardId, cardType: "interactive", title: "Relativity: True or False" },
  { id: "lib-game-1" as CardId, cardType: "games", title: "Cell Biology Vocabulary Match" },
  { id: "lib-game-2" as CardId, cardType: "games", title: "Apollo 11 Mission Sequence" },
  { id: "lib-game-3" as CardId, cardType: "games", title: "Periodic Elements Memory Game" },
  { id: "lib-layout-split" as CardId, cardType: "layout-split", title: "Split — Two Equal Columns" },
  { id: "lib-layout-stack" as CardId, cardType: "layout-stack", title: "Stack — Primary / Secondary Rows" },
  { id: "lib-layout-feature" as CardId, cardType: "layout-feature", title: "Feature — Anchor + Content + Strip" },
  { id: "lib-layout-sidebar" as CardId, cardType: "layout-sidebar", title: "Sidebar — 30 / 70 Columns" },
  { id: "lib-layout-quad" as CardId, cardType: "layout-quad", title: "Quad — 2 × 2 Grid" },
  { id: "lib-layout-mosaic" as CardId, cardType: "layout-mosaic", title: "Mosaic — 3 × 3 Grid" },
  { id: "lib-layout-triptych" as CardId, cardType: "layout-triptych", title: "Triptych — Three Equal Columns" },
  { id: "lib-layout-trirow" as CardId, cardType: "layout-trirow", title: "Trirow — Header / Body / Footer" },
  { id: "lib-layout-banner" as CardId, cardType: "layout-banner", title: "Banner — Full-Width Header + Two Columns" },
  { id: "lib-layout-broadside" as CardId, cardType: "layout-broadside", title: "Broadside — Full-Width Header + Three Cols" },
  { id: "lib-layout-tower" as CardId, cardType: "layout-tower", title: "Tower — Wide Feature + Three Side Panels" },
  { id: "lib-layout-pinboard" as CardId, cardType: "layout-pinboard", title: "Pinboard — Header + 2 × 2 Blocks" },
  { id: "lib-layout-annotated" as CardId, cardType: "layout-annotated", title: "Annotated — Margin Notes + 2 × 2 Grid" },
  { id: "lib-layout-sixgrid" as CardId, cardType: "layout-sixgrid", title: "Six-Grid — 3 × 2 Storyboard" },
]

export const CARD_TYPE_COLORS: Record<CardType, { bg: string; text: string }> = {
  text: { bg: "bg-primary/10", text: "text-primary" },
  image: { bg: "bg-[#5c9970]/10", text: "text-[#5c9970]" },
  audio: { bg: "bg-[#b87c5c]/10", text: "text-[#b87c5c]" },
  video: { bg: "bg-[#6b8fc4]/10", text: "text-[#6b8fc4]" },
  animation: { bg: "bg-[#b87070]/10", text: "text-[#b87070]" },
  dataset: { bg: "bg-primary/10", text: "text-primary" },
  embed: { bg: "bg-muted", text: "text-muted-foreground" },
  flashcards: { bg: "bg-[#a89450]/10", text: "text-[#a89450]" },
  "code-snippet": { bg: "bg-neutral-900/10", text: "text-neutral-700" },
  "model-3d": { bg: "bg-[#a89450]/10", text: "text-[#a89450]" },
  map: { bg: "bg-[#5c9970]/10", text: "text-[#5c9970]" },
  chart: { bg: "bg-[#b87c5c]/10", text: "text-[#b87c5c]" },
  diagram: { bg: "bg-[#6b8fc4]/10", text: "text-[#6b8fc4]" },
  media: { bg: "bg-[#5c9970]/10", text: "text-[#5c9970]" },
  document: { bg: "bg-muted", text: "text-muted-foreground" },
  table: { bg: "bg-[#b87c5c]/10", text: "text-[#b87c5c]" },
  "rich-sim": { bg: "bg-[#a89450]/10", text: "text-[#a89450]" },
  "village-3d": { bg: "bg-[#a89450]/10", text: "text-[#a89450]" },
  interactive: { bg: "bg-[#5c9970]/10", text: "text-[#5c9970]" },
  form: { bg: "bg-[#5c9970]/10", text: "text-[#5c9970]" },
  "voice-recorder": { bg: "bg-[#b87c5c]/10", text: "text-[#b87c5c]" },
  sorter: { bg: "bg-[#6b8fc4]/10", text: "text-[#6b8fc4]" },
  games: { bg: "bg-[#6b8fc4]/10", text: "text-[#6b8fc4]" },
  chat: { bg: "bg-[#b87070]/10", text: "text-[#b87070]" },
  "text-editor": { bg: "bg-primary/10", text: "text-primary" },
  "code-editor": { bg: "bg-muted", text: "text-foreground/70" },
  whiteboard: { bg: "bg-[#5c9970]/10", text: "text-[#5c9970]" },
  timeline: { bg: "bg-primary/10", text: "text-primary" },
  legend: { bg: "bg-[#5c9970]/10", text: "text-[#5c9970]" },
  "layout-split": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-stack": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-feature": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-sidebar": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-quad": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-mosaic": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-triptych": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-trirow": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-banner": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-broadside": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-tower": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-pinboard": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-annotated": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-sixgrid": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-comparison": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-stepped": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-hero": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-dialogue": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-gallery": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-spotlight": { bg: "bg-muted", text: "text-muted-foreground" },
  "layout-flipcard": { bg: "bg-muted", text: "text-muted-foreground" },
}

export const TYPE_LABEL: Partial<Record<CardType, string>> = {
  embed: "Embed",
  flashcards: "Flashcard Set",
  "code-snippet": "Code Snippet",
  "rich-sim": "Simulation",
  "village-3d": "3D Scene",
  interactive: "Assessment",
  form: "Form",
  "voice-recorder": "Voice Recorder",
  sorter: "Sorter / Matcher",
  chat: "Character",
  "text-editor": "Writing Pad",
  "code-editor": "Code Editor",
  whiteboard: "Whiteboard",
  "layout-split": "Split",
  "layout-stack": "Stack",
  "layout-feature": "Feature",
  "layout-sidebar": "Sidebar",
  "layout-quad": "Quad",
  "layout-mosaic": "Mosaic",
  "layout-triptych": "Triptych",
  "layout-trirow": "Trirow",
  "layout-banner": "Banner",
  "layout-broadside": "Broadside",
  "layout-tower": "Tower",
  "layout-pinboard": "Pinboard",
  "layout-annotated": "Annotated",
  "layout-sixgrid": "Six-Grid",
  "layout-comparison": "Comparison",
  "layout-stepped": "Stepped",
  "layout-hero": "Hero",
  "layout-dialogue": "Dialogue",
  "layout-gallery": "Gallery",
  "layout-spotlight": "Spotlight",
  "layout-flipcard": "Flipcard",
}

export const TYPE_ICONS: Partial<Record<CardType, ComponentType<{ size?: number; className?: string }>>> = {
  text: FileText,
  image: ImageIcon,
  audio: AudioLines,
  video: PlayCircle,
  animation: Film,
  embed: ExternalLink,
  flashcards: ClipboardList,
  "code-snippet": FileCode2,
  "model-3d": Box,
  document: FileText,
  map: MapIcon,
  chart: LineChart,
  diagram: Network,
  table: Table2,
  dataset: Database,
  "rich-sim": Sparkles,
  interactive: HelpCircle,
  form: ClipboardList,
  "voice-recorder": Mic,
  sorter: ArrowLeftRight,
  games: Gamepad2,
  chat: Bot,
  "text-editor": FileText,
  "code-editor": Code2,
  whiteboard: PenTool,
  "layout-split": Columns2,
  "layout-stack": Rows2,
  "layout-feature": Layout,
  "layout-sidebar": PanelLeft,
  "layout-quad": LayoutGrid,
  "layout-mosaic": Grid3X3,
  "layout-triptych": Columns3,
  "layout-trirow": Rows3,
  "layout-banner": LayoutPanelTop,
  "layout-broadside": LayoutTemplate,
  "layout-tower": LayoutPanelLeft,
  "layout-pinboard": LayoutDashboard,
  "layout-annotated": PanelLeftOpen,
  "layout-sixgrid": Grid3x2,
  "layout-comparison": Columns2,
  "layout-stepped": Rows3,
  "layout-hero": LayoutPanelTop,
  "layout-dialogue": Columns2,
  "layout-gallery": Grid3X3,
  "layout-spotlight": Layout,
  "layout-flipcard": LayoutTemplate,
}