version: '3.8'

services:
  # Development server
  neptino-dev:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - neptino-network

  # Production build and serve
  neptino-prod:
    build:
      context: .
      target: production
    ports:
      - "8080:80"
    networks:
      - neptino-network

  # PostgreSQL database
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: neptino
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    networks:
      - neptino-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d neptino"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  neptino-network:
    driver: bridge

volumes:
  postgres_data:
