# Optimized Docker Compose for LOCAL DEVELOPMENT
# Only runs PostgreSQL - everything else runs on host
# Usage: docker-compose -f docker-compose.local.yml up

version: '3.8'

services:
  # PostgreSQL database ONLY (for local development)
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: neptino
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    networks:
      - neptino-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d neptino"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  neptino-network:
    driver: bridge

volumes:
  postgres_data_local:
