export interface TemplateBlockConfig {
    id: string;
    type:
    | "header"
    | "program"
    | "resources"
    | "content"
    | "assignment"
    | "scoring"
    | "footer";
    label: string;
    icon: string;
    defaultConfig: Record<string, any>;
    configFields: TemplateConfigField[];
}

export interface TemplateConfigField {
    name: string;
    label: string;
    type: "text" | "textarea" | "select" | "checkbox" | "color" | "number";
    options?: { value: string; label: string }[];
    defaultValue?: any;
    required?: boolean;
}

export const TEMPLATE_BLOCKS: TemplateBlockConfig[] = [
    {
        id: "header",
        type: "header",
        label: "Header",
        icon: "header",
        defaultConfig: {
            showTitle: true,
            showSubtitle: true,
            backgroundColor: "#ffffff",
            textColor: "#333333",
        },
        configFields: [
            {
                name: "showTitle",
                label: "Show Title",
                type: "checkbox",
                defaultValue: true,
            },
            {
                name: "showSubtitle",
                label: "Show Subtitle",
                type: "checkbox",
                defaultValue: true,
            },
            {
                name: "backgroundColor",
                label: "Background Color",
                type: "color",
                defaultValue: "#ffffff",
            },
            {
                name: "textColor",
                label: "Text Color",
                type: "color",
                defaultValue: "#333333",
            },
        ],
    },
    {
        id: "program",
        type: "program",
        label: "Program",
        icon: "program",
        defaultConfig: {
            competence: true,
            topic: true,
            objective: true,
            task: true,
            program_method: true,
            program_social_form: true,
            program_time: true,
        },
        configFields: [
            {
                name: "competence",
                label: "Competence",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "topic",
                label: "Topic",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "objective",
                label: "Objective",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "task",
                label: "Task",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "program_method",
                label: "Method",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "program_social_form",
                label: "Social form",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "program_time",
                label: "Time",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
        ],
    },
    {
        id: "resources",
        type: "resources",
        label: "Resources",
        icon: "resources",
        defaultConfig: {
            allowFiles: true,
            allowLinks: true,
            allowVideos: true,
            maxFiles: 10,
        },
        configFields: [
            {
                name: "allowFiles",
                label: "Allow File Uploads",
                type: "checkbox",
                defaultValue: true,
            },
            {
                name: "allowLinks",
                label: "Allow External Links",
                type: "checkbox",
                defaultValue: true,
            },
            {
                name: "allowVideos",
                label: "Allow Video Embeds",
                type: "checkbox",
                defaultValue: true,
            },
            {
                name: "maxFiles",
                label: "Maximum Files",
                type: "number",
                defaultValue: 10,
            },
        ],
    },
    {
        id: "content",
        type: "content",
        label: "Content",
        icon: "content",
        defaultConfig: {
            editor: "rich-text",
            allowMedia: true,
            allowTables: true,
            competence: true,
            competence_time: true,
            topic: true,
            topic_time: true,
            objective: true,
            objective_time: true,
            task: true,
            task_time: true,
            instruction_area: true,
            instruction_method: true,
            instruction_social_form: true,
            student_area: true,
            student_method: true,
            student_social_form: true,
            teacher_area: true,
            teacher_method: true,
            teacher_social_form: true,
            include_project: false,
        },
        configFields: [
            {
                name: "editor",
                label: "Editor Type",
                type: "select",
                options: [
                    { value: "rich-text", label: "Rich Text Editor" },
                    { value: "markdown", label: "Markdown Editor" },
                    { value: "plain-text", label: "Plain Text" },
                ],
                defaultValue: "rich-text",
            },
            {
                name: "allowMedia",
                label: "Allow Media Uploads",
                type: "checkbox",
                defaultValue: true,
            },
            {
                name: "allowTables",
                label: "Allow Tables",
                type: "checkbox",
                defaultValue: true,
            },
            {
                name: "competence",
                label: "Competence",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "competence_time",
                label: "Time",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "topic",
                label: "Topic",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "topic_time",
                label: "Time",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "objective",
                label: "Objective",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "objective_time",
                label: "Time",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "task",
                label: "Task",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "task_time",
                label: "Time",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "instruction_area",
                label: "Instruction Area",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "instruction_method",
                label: "Method",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "instruction_social_form",
                label: "Social form",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "student_area",
                label: "Student Area",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "student_method",
                label: "Method",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "student_social_form",
                label: "Social form",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "teacher_area",
                label: "Teacher Area",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "teacher_method",
                label: "Method",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "teacher_social_form",
                label: "Social form",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "include_project",
                label: "Include Project",
                type: "checkbox",
                defaultValue: false,
            },
        ],
    },
    {
        id: "assignment",
        type: "assignment",
        label: "Assignment",
        icon: "assignment",
        defaultConfig: {
            allowSubmissions: true,
            requireDueDate: true,
            enableGrading: true,
            maxSubmissions: 1,
            competence: true,
            competence_time: true,
            topic: true,
            topic_time: true,
            objective: true,
            objective_time: true,
            task: true,
            task_time: true,
            instruction_area: true,
            instruction_method: true,
            instruction_social_form: true,
            student_area: true,
            student_method: true,
            student_social_form: true,
            teacher_area: true,
            teacher_method: true,
            teacher_social_form: true,
            include_project: false,
        },
        configFields: [
            {
                name: "allowSubmissions",
                label: "Allow Student Submissions",
                type: "checkbox",
                defaultValue: true,
            },
            {
                name: "requireDueDate",
                label: "Require Due Date",
                type: "checkbox",
                defaultValue: true,
            },
            {
                name: "enableGrading",
                label: "Enable Grading",
                type: "checkbox",
                defaultValue: true,
            },
            {
                name: "maxSubmissions",
                label: "Maximum Submissions",
                type: "number",
                defaultValue: 1,
            },
            {
                name: "competence",
                label: "Competence",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "competence_time",
                label: "Time",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "topic",
                label: "Topic",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "topic_time",
                label: "Time",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "objective",
                label: "Objective",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "objective_time",
                label: "Time",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "task",
                label: "Task",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "task_time",
                label: "Time",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "instruction_area",
                label: "Instruction Area",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "instruction_method",
                label: "Method",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "instruction_social_form",
                label: "Social form",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "student_area",
                label: "Student Area",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "student_method",
                label: "Method",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "student_social_form",
                label: "Social form",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "teacher_area",
                label: "Teacher Area",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "teacher_method",
                label: "Method",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "teacher_social_form",
                label: "Social form",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "include_project",
                label: "Include Project",
                type: "checkbox",
                defaultValue: false,
            },
        ],
    },
    {
        id: "scoring",
        type: "scoring",
        label: "Scoring",
        icon: "assessment",
        defaultConfig: {
            criteria: true,
            max_points: true,
            passing_threshold: false,
            feedback_guidelines: false,
            rubric_link: false,
        },
        configFields: [
            {
                name: "criteria",
                label: "Criteria",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "max_points",
                label: "Max Points",
                type: "checkbox",
                defaultValue: true,
                required: true,
            },
            {
                name: "passing_threshold",
                label: "Passing Threshold",
                type: "checkbox",
                defaultValue: false,
            },
            {
                name: "feedback_guidelines",
                label: "Feedback Guidelines",
                type: "checkbox",
                defaultValue: false,
            },
            {
                name: "rubric_link",
                label: "Rubric Link",
                type: "checkbox",
                defaultValue: false,
            },
        ],
    },
    {
        id: "footer",
        type: "footer",
        label: "Footer",
        icon: "footer",
        defaultConfig: {
            showCredits: true,
            showDate: true,
            showContact: false,
        },
        configFields: [
            {
                name: "showCredits",
                label: "Show Credits",
                type: "checkbox",
                defaultValue: true,
            },
            {
                name: "showDate",
                label: "Show Creation Date",
                type: "checkbox",
                defaultValue: true,
            },
            {
                name: "showContact",
                label: "Show Contact Information",
                type: "checkbox",
                defaultValue: false,
            },
        ],
    },
];
